<!-- Generated by vuejs gem ~> github.com/ytbryan/vuejs -->
<!-- To generate another component part, Please run `rails generate vue something` -->

<template> 
  <div id="employees">
    <p>{{ message }}</p>
    <!-- <button @click="onClick">click this</button> -->
  </div>
</template>

<script>
export default {
  props: ['employeeList'],
  data: function () {
    return {
      message: "Hello employees!"
    }
  }, 
  watch: {
    onCreated: function(response){
      this.items = response.data
    }
  },
  methods: {
    //uncomment the <button  @click="onClick"> at your template
    onClick: function(){
      console.log("clicked")
    }
  }, 
  computed: {

  },
  // components: {},
  // mixins: [], 
  // directives: {}, 
  // filters: {},
  // asyncComputed: {},
}
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
