<!-- Generated by vuejs gem ~> github.com/ytbryan/vuejs -->
<!-- To generate another component part, Please run `rails generate vue something` -->

<template> 
  <div id="projects">
    <p>{{ message }}</p>
    <v-app id="inspire">
      <div class="text-xs-center">
        <v-pagination
                v-model="pagination.page"
                :length="pagination.pages"
                @input="next"
        ></v-pagination>
      </div>

      <v-data-table
              :headers="headers"
              :items="projects"
              hide-actions
              class="elevation-1"
      >
        <template slot="items" slot-scope="props">
          <td>{{ props.item.name }}</td>
          <td class="text-xs-right">{{ props.item.description }}</td>
        </template>
      </v-data-table>
    </v-app>
  </div>
</template>

<script>
  import axios from 'axios';

  export default {
    // props: {},
    data: function () {
      return {
        message: "Hello projects!",
        pagination: JSON.parse(erb('pagination')),
        projects: JSON.parse(erb('projects')),
          headers: [
              {
                  text: 'Name',
                  align: 'left',
                  value: 'name'
              },
              { text: 'Description', value: 'description' }
          ],
      }
    },
    watch: {
      onCreated: function(response){
        this.items = response.data
      }
    },
    methods: {
      //uncomment the <button  @click="onClick"> at your template
      next: function(page){
        console.log("getting next page:", page)
        axios.get('/projects.json', { params: { page: page }})
            .then(response => {
                // JSON responses are automatically parsed.
                this.projects = response.data
            })
            .catch(e => {
                console.log(e)
            })

          return this.projects
      }
    },
    computed: {

    },
    // components: {},
    // mixins: [],
    // directives: {},
    // filters: {},
    // asyncComputed: {},
  }
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
