<!-- Generated by vuejs gem ~> github.com/ytbryan/vuejs -->
<!-- To generate another component part, Please run `rails generate vue something` -->

<template> 
  <div id="projects">
    <p>{{ message }}</p>
    <v-app id="inspire">
      <div class="text-xs-center">
        <v-pagination
                v-model="pagination.page"
                :length="pagination.pages"
                @input="next"
        ></v-pagination>
      </div>

      <v-data-table
              :headers="headers"
              :items="projects"
              hide-actions
              class="elevation-1"
              :total-items="totalProjects"
              :pagination.sync="pagination"
      >
        <template slot="items" slot-scope="props">
          <td>{{ props.item.name }}</td>
          <td class="text-xs-right">{{ props.item.description }}</td>
        </template>
      </v-data-table>
    </v-app>
  </div>
</template>

<script>
  import axios from 'axios';

  export default {
    // props: {},
    data: function () {
      return {
        message: "",
        totalProjects: JSON.parse(erb('total_items')),
        pagination: JSON.parse(erb('pagination')),
        projects: JSON.parse(erb('projects')),
        headers: [
            {
                text: 'Name',
                align: 'left',
                value: 'name'
            },
            { text: 'Description', value: 'description', align: 'left'}
        ],
      }
    },
    watch: {
        "pagination": {
            handler () {
                let self = this
                console.log("Pagination:", this.pagination)
                let pagination = this.pagination
                return axios.get('/projects.json', { params: {
                        page: pagination.page,
                        sort_by: pagination.sortBy,
                        descending: pagination.descending }})
                    .then(response => {
                        self.projects = response.data.data
                        // may need to set totalItems also
                        self.pagination.page = response.data.pagination.page
                        self.pagination.pages = response.data.pagination.pages
                    })
                    .catch(e => {
                        console.log(e)
                    })
            }
        }
    },
    methods: {
      next: function(page){
        console.log("in next")
        let self = this
        let pagination = this.pagination
        return axios.get('/projects.json', { params: {
                page: page,
                sort_by: pagination.sortBy,
                descending: pagination.descending }})
            .then(response => {
                self.projects = response.data.data
                // may need to set totalItems also
                self.pagination.page = response.data.pagination.page
                self.pagination.pages = response.data.pagination.pages
            })
            .catch(e => {
                console.log(e)
            })
      }
    },
    computed: {
    },
    // components: {},
    // mixins: [],
    // directives: {},
    // filters: {},
    // asyncComputed: {},
  }
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
