// Generated by Vuejs gem ~> github.com/ytbryan/vuejs
// Run this example by adding  <%= javascript_pack_tag "employees" %> into your 
// Rails' view
// To generate another component part with turbolinks, please run `rails generate vue something --turbolinks`

import TurbolinksAdapter from 'vue-turbolinks';
import Vue from 'vue'
import App from '../parts/employees.vue'

Vue.use(TurbolinksAdapter)
document.addEventListener('turbolinks:load', () => {
    let employees_dom = document.querySelector("#employees")
    if (employees_dom !== null) {
        const employees = new Vue({
            render: h => h(App)
        }).$mount('#employees')
    }

})