//Generated by Vuejs gem ~> github.com/ytbryan/vuejs
//Run this example by adding  <%= javascript_pack_tag "products" %> into your 
//Rails' view
//To generate another component part, please run `rails generate vue something`

import Vue from 'vue'
import App from '../parts/products.vue'

document.addEventListener('DOMContentLoaded', () => {
  document.body.appendChild(document.createElement('products'))
  const products = new Vue({
    render: h => h(App)
  }).$mount('products')
  console.log({products})
})