// Generated by Vuejs gem ~> github.com/ytbryan/vuejs
// Run this example by adding  <%= javascript_pack_tag "projects" %> into your 
// Rails' view
// To generate another component part with turbolinks, please run `rails generate vue something --turbolinks`

import TurbolinksAdapter from 'vue-turbolinks';
import Vue from 'vue'
import App from '../parts/projects.vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css';
import 'material-design-icons-iconfont/dist/material-design-icons.css'


Vue.use(TurbolinksAdapter)
Vue.use(Vuetify)

document.addEventListener('turbolinks:load', () => {
    let projects_dom = document.querySelector("#projects")
    if (projects_dom !== null ) {
        const projects = new Vue({
            render: h => h(App)
        }).$mount('#projects')
    }
})